ccvpress:
  build: ./ccvpress
  links:
    - ccvmysql:mysql
  ports:
    - 80:80
  volumes:
    - /home/ccvAdmin/wwwData:/var/www/html
  mem_limit: 200m
ccvmysql:
  build: ./ccvmysql
  environment:
    MYSQL_ROOT_PASSWORD: insecurepass
  volumes:
    - /home/ccvAdmin/mysqlData:/var/lib/mysql
  mem_limit: 200m
